on:
  workflow_dispatch:  

jobs:
  tests_e2e:
    name: Run tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright dependencies
        uses: microsoft/playwright-github-action@v1

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright API tests
        run: npm run apiTests
